Workaround "AttributeError: 'NoneType' object has no attribute 'text'"
It seems like some stories do not have the "JsReport" and the "JsStar" html tags in the response.
As a workaround these fields will simply be set to zero, since they are not important anyways.